-- AlterTable
ALTER TABLE "monthly_usages" ADD COLUMN     "aiLimit" INTEGER NOT NULL DEFAULT 100,
ADD COLUMN     "blogLimit" INTEGER NOT NULL DEFAULT 2,
ADD COLUMN     "emailLimit" INTEGER NOT NULL DEFAULT 20,
ADD COLUMN     "otpLimit" INTEGER NOT NULL DEFAULT 10,
ADD COLUMN     "pushLimit" INTEGER NOT NULL DEFAULT 2,
ADD COLUMN     "smsLimit" INTEGER NOT NULL DEFAULT 0,
ADD COLUMN     "storageLimit" INTEGER NOT NULL DEFAULT 1,
ADD COLUMN     "subscriberLimit" INTEGER NOT NULL DEFAULT 100;
