// components/notifications/NotificationTemplate.tsx
import { NotificationType, NotificationPriority } from "@/lib/generated/prisma/enums";

export interface NotificationTemplate {
  type: NotificationType;
  title: string;
  message: string;
  shortMessage: string;
  actionLabel?: string;
  actionUrl?: string;
  priority: NotificationPriority;
  icon?: string;
  color?: string;
}

export const notificationTemplates: Record<NotificationType, NotificationTemplate> = {
  // Billing & Subscription
  SUBSCRIPTION_CREATED: {
    type: 'SUBSCRIPTION_CREATED',
    title: 'Subscription Created',
    message: 'Your {{plan}} subscription has been successfully created. Welcome to {{workspace}}!',
    shortMessage: 'Subscription activated',
    actionLabel: 'View Subscription',
    actionUrl: '/dashboard',
    priority: 'MEDIUM',
    icon: '🎉',
    color: 'green',
  },
  SUBSCRIPTION_RENEWED: {
    type: 'SUBSCRIPTION_RENEWED',
    title: 'Subscription Renewed',
    message: 'Your {{plan}} subscription has been renewed for ₦{{amount}}.',
    shortMessage: 'Subscription renewed',
    actionLabel: 'View Invoice',
    actionUrl: '/dashboard',
    priority: 'MEDIUM',
    icon: '🔄',
    color: 'blue',
  },
  SUBSCRIPTION_CANCELLED: {
    type: 'SUBSCRIPTION_CANCELLED',
    title: 'Subscription Cancelled',
    message: 'Your {{plan}} subscription has been cancelled. You will have access until {{endDate}}.',
    shortMessage: 'Subscription cancelled',
    actionLabel: 'Reactivate',
    actionUrl: '/dashboard',
    priority: 'HIGH',
    icon: '❌',
    color: 'red',
  },
  SUBSCRIPTION_EXPIRING: {
    type: 'SUBSCRIPTION_EXPIRING',
    title: 'Subscription Expiring Soon',
    message: 'Your {{plan}} subscription will expire in {{days}} days. Please renew to avoid service interruption.',
    shortMessage: 'Subscription expiring soon',
    actionLabel: 'Renew Now',
    actionUrl: '/dashboard',
    priority: 'HIGH',
    icon: '⚠️',
    color: 'yellow',
  },
  SUBSCRIPTION_FAILED: {
    type: 'SUBSCRIPTION_FAILED',
    title: 'Payment Failed',
    message: 'Your payment of ₦{{amount}} for {{plan}} plan failed. Please update your payment method.',
    shortMessage: 'Payment failed',
    actionLabel: 'Update Payment',
    actionUrl: '/dashboard',
    priority: 'URGENT',
    icon: '❌',
    color: 'red',
  },
  PAYMENT_SUCCESS: {
    type: 'PAYMENT_SUCCESS',
    title: 'Payment Successful',
    message: 'Your payment of ₦{{amount}} for {{plan}} plan was successful.',
    shortMessage: 'Payment successful',
    actionLabel: 'View Receipt',
    actionUrl: '/dashboard',
    priority: 'MEDIUM',
    icon: '✅',
    color: 'green',
  },
  PAYMENT_FAILED: {
    type: 'PAYMENT_FAILED',
    title: 'Payment Failed',
    message: 'Your payment of ₦{{amount}} for {{plan}} plan failed. Please try again or use a different payment method.',
    shortMessage: 'Payment failed',
    actionLabel: 'Try Again',
    actionUrl: '/dashboard',
    priority: 'URGENT',
    icon: '❌',
    color: 'red',
  },
  PAYMENT_REFUNDED: {
    type: 'PAYMENT_REFUNDED',
    title: 'Payment Refunded',
    message: 'Your payment of ₦{{amount}} has been refunded to your {{paymentMethod}}.',
    shortMessage: 'Payment refunded',
    actionLabel: 'View Details',
    actionUrl: '/dashboard',
    priority: 'MEDIUM',
    icon: '↩️',
    color: 'blue',
  },
  INVOICE_READY: {
    type: 'INVOICE_READY',
    title: 'Invoice Ready',
    message: 'Your invoice #{{invoiceNumber}} for ₦{{amount}} is now available.',
    shortMessage: 'New invoice',
    actionLabel: 'View Invoice',
    actionUrl: '/dashboard',
    priority: 'LOW',
    icon: '📄',
    color: 'gray',
  },
  CARD_EXPIRING: {
    type: 'CARD_EXPIRING',
    title: 'Card Expiring Soon',
    message: 'Your card ending in {{last4}} expires on {{expMonth}}/{{expYear}}. Please update your payment method.',
    shortMessage: 'Card expiring',
    actionLabel: 'Update Card',
    actionUrl: '/dashboard',
    priority: 'HIGH',
    icon: '💳',
    color: 'yellow',
  },
  CARD_EXPIRED: {
    type: 'CARD_EXPIRED',
    title: 'Card Expired',
    message: 'Your card ending in {{last4}} has expired. Please update your payment method to avoid service interruption.',
    shortMessage: 'Card expired',
    actionLabel: 'Update Card',
    actionUrl: '/dashboard',
    priority: 'URGENT',
    icon: '💳',
    color: 'red',
  },
  PAYMENT_METHOD_UPDATED: {
    type: 'PAYMENT_METHOD_UPDATED',
    title: 'Payment Method Updated',
    message: 'Your payment method has been updated successfully.',
    shortMessage: 'Payment method updated',
    actionLabel: 'View Methods',
    actionUrl: '/dashboard',
    priority: 'LOW',
    icon: '💳',
    color: 'green',
  },

  // Promo & Credits
  PROMO_APPLIED: {
    type: 'PROMO_APPLIED',
    title: 'Promo Code Applied',
    message: 'Promo code {{code}} applied successfully. You saved {{discount}}!',
    shortMessage: 'Promo applied',
    actionLabel: 'View Savings',
    actionUrl: '/dashboard',
    priority: 'LOW',
    icon: '🏷️',
    color: 'purple',
  },
  PROMO_EXPIRING: {
    type: 'PROMO_EXPIRING',
    title: 'Promo Code Expiring',
    message: 'Your promo code {{code}} will expire in {{days}} days.',
    shortMessage: 'Promo expiring',
    actionLabel: 'Use Now',
    actionUrl: '/dashboard/billing',
    priority: 'MEDIUM',
    icon: '⏰',
    color: 'yellow',
  },
  CREDITS_ADDED: {
    type: 'CREDITS_ADDED',
    title: 'Credits Added',
    message: '{{amount}} credits have been added to your account.',
    shortMessage: 'Credits added',
    actionLabel: 'View Balance',
    actionUrl: '/dashboard',
    priority: 'LOW',
    icon: '💰',
    color: 'green',
  },
  CREDITS_LOW: {
    type: 'CREDITS_LOW',
    title: 'Low Credits',
    message: 'You have only {{amount}} credits remaining. Purchase more to avoid service interruption.',
    shortMessage: 'Low credits',
    actionLabel: 'Buy Credits',
    actionUrl: '/dashboard',
    priority: 'HIGH',
    icon: '⚠️',
    color: 'yellow',
  },

  // Workspace & Team
  WORKSPACE_INVITE: {
    type: 'WORKSPACE_INVITE',
    title: 'Workspace Invitation',
    message: 'You have been invited to join {{workspace}} by {{inviter}}.',
    shortMessage: 'Workspace invite',
    actionLabel: 'View Invite',
    actionUrl: '/dashboard',
    priority: 'MEDIUM',
    icon: '👥',
    color: 'blue',
  },
  TEAM_MEMBER_JOINED: {
    type: 'TEAM_MEMBER_JOINED',
    title: 'Team Member Joined',
    message: '{{name}} ({{email}}) has joined your workspace.',
    shortMessage: 'New team member',
    actionLabel: 'View Team',
    actionUrl: '/dashboard',
    priority: 'LOW',
    icon: '👤',
    color: 'green',
  },
  TEAM_MEMBER_LEFT: {
    type: 'TEAM_MEMBER_LEFT',
    title: 'Team Member Left',
    message: '{{name}} ({{email}}) has left your workspace.',
    shortMessage: 'Team member left',
    actionLabel: 'View Team',
    actionUrl: '/dashboard',
    priority: 'LOW',
    icon: '👋',
    color: 'gray',
  },
  ROLE_CHANGED: {
    type: 'ROLE_CHANGED',
    title: 'Role Changed',
    message: 'Your role in {{workspace}} has been changed to {{role}}.',
    shortMessage: 'Role changed',
    actionLabel: 'View Workspace',
    actionUrl: '/dashboard',
    priority: 'MEDIUM',
    icon: '🔑',
    color: 'blue',
  },

  // System & Security
  SYSTEM_ALERT: {
    type: 'SYSTEM_ALERT',
    title: 'System Alert',
    message: '{{message}}',
    shortMessage: 'System alert',
    actionLabel: 'Learn More',
    actionUrl: '/dashboard',
    priority: 'URGENT',
    icon: '🚨',
    color: 'red',
  },
  SECURITY_ALERT: {
    type: 'SECURITY_ALERT',
    title: 'Security Alert',
    message: '{{message}}',
    shortMessage: 'Security alert',
    actionLabel: 'Review',
    actionUrl: '/dashboard',
    priority: 'URGENT',
    icon: '🛡️',
    color: 'red',
  },
  LOGIN_FROM_NEW_DEVICE: {
    type: 'LOGIN_FROM_NEW_DEVICE',
    title: 'New Login Detected',
    message: 'A new login was detected from {{location}} using {{device}}.',
    shortMessage: 'New login',
    actionLabel: 'Review Activity',
    actionUrl: '/dashboard',
    priority: 'HIGH',
    icon: '🔐',
    color: 'blue',
  },
  PASSWORD_CHANGED: {
    type: 'PASSWORD_CHANGED',
    title: 'Password Changed',
    message: 'Your password was changed successfully.',
    shortMessage: 'Password changed',
    actionLabel: 'Review Security',
    actionUrl: '/dashboard/security',
    priority: 'HIGH',
    icon: '🔑',
    color: 'green',
  },
  EMAIL_VERIFIED: {
    type: 'EMAIL_VERIFIED',
    title: 'Email Verified',
    message: 'Your email address has been successfully verified.',
    shortMessage: 'Email verified',
    actionLabel: 'Continue',
    actionUrl: '/dashboard',
    priority: 'LOW',
    icon: '✅',
    color: 'green',
  },
  ACCOUNT_LOCKED: {
    type: 'ACCOUNT_LOCKED',
    title: 'Account Locked',
    message: 'Your account has been locked due to multiple failed login attempts.',
    shortMessage: 'Account locked',
    actionLabel: 'Contact Support',
    actionUrl: '/support',
    priority: 'URGENT',
    icon: '🔒',
    color: 'red',
  },

  // API & Usage
  USAGE_LIMIT_APPROACHING: {
    type: 'USAGE_LIMIT_APPROACHING',
    title: 'Usage Limit Approaching',
    message: 'You have used {{percentage}}% of your {{resource}} limit for this month.',
    shortMessage: 'Usage limit approaching',
    actionLabel: 'View Usage',
    actionUrl: '/dashboard',
    priority: 'MEDIUM',
    icon: '📊',
    color: 'yellow',
  },
  USAGE_LIMIT_REACHED: {
    type: 'USAGE_LIMIT_REACHED',
    title: 'Usage Limit Reached',
    message: 'You have reached your {{resource}} limit for this month. Upgrade to continue.',
    shortMessage: 'Usage limit reached',
    actionLabel: 'Upgrade',
    actionUrl: '/dashboard',
    priority: 'HIGH',
    icon: '⚠️',
    color: 'red',
  },
  API_KEY_CREATED: {
    type: 'API_KEY_CREATED',
    title: 'API Key Created',
    message: 'A new API key was created for {{workspace}}.',
    shortMessage: 'API key created',
    actionLabel: 'View Keys',
    actionUrl: '/dashboard',
    priority: 'MEDIUM',
    icon: '🔑',
    color: 'blue',
  },
  API_KEY_REVOKED: {
    type: 'API_KEY_REVOKED',
    title: 'API Key Revoked',
    message: 'An API key has been revoked for {{workspace}}.',
    shortMessage: 'API key revoked',
    actionLabel: 'View Keys',
    actionUrl: '/dashboard',
    priority: 'MEDIUM',
    icon: '❌',
    color: 'orange',
  },
};